on:
  push:
    branches: [ main ]

jobs:
  fixinator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundeo/fixinator-docker/fixinator:latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run Fixinator
      run: box fixinator resultFile=fixinator-report.html resultFormat=html failOnIssues=false
      env:
        FIXINATOR_API_KEY: ${{ secrets.FIXINATOR_API_KEY }}
    - uses: actions/upload-artifact@v3
      with:
        name: fixinator-report
        path: fixinator-report.html

