name: Artifact
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  fixinator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundeo/fixinator-docker/fixinator:latest
    
    steps:
    - name: Install git client
      run: apk add git
    - uses: actions/checkout@v2
      with: 
       fetch-depth: 2
    - name: Run Fixinator
      run: box fixinator resultFile=fixinator-report.pdf resultFormat=pdf failOnIssues=false
      env:
        FIXINATOR_API_KEY: ${{ secrets.FIXINATOR_API_KEY }}
    - uses: actions/upload-artifact@v3
      with:
        name: fixinator-report
        path: fixinator-report.pdf

